{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "bb50591d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "# from .manager import validate_project_id, get_dataframe_query\n",
    "# from . import connection_manager\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "7cf7c69b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_dataframe(ds_name, project_id=\"a88ce554-9358-4397-8b8d-14c972807df5\", row_count=-1, strategy=\"top\", user_id=\"1001\",\n",
    "                  filter_condition=None):\n",
    "    \"\"\"\n",
    "    Param:\n",
    "        ds_name,\n",
    "        project_id=os.getenv(\"project_id\"),\n",
    "        row_count=-1,\n",
    "        strategy=\"top\"\n",
    "        user_id=\"1001\"\n",
    "    To get pandas dataframe.\n",
    "    Need to install mosaic-connector-python for reading dataframe using connector backend,\n",
    "    git+https://gitlab+deploy-token-14:myUpFE_XRxShG53Hs6tV@git.lti-aiq.in/mosaic-decisions-2-0/mosaic-connector-python.git@1.0.29.3\n",
    "    \"\"\"\n",
    "    try:\n",
    "        connection_manager=\"http://fdc-project-manager:80/project-manager\"\n",
    "        project_id = validate_project_id(project_id)\n",
    "        url = f\"{connection_manager}/connections/api/External/v2/external/getConnConfig/\" \\\n",
    "              f\"{ds_name}/fdcuser/{project_id}\"    # user id hard coded, as it's not being used in API code.\n",
    "        pri\n",
    "        connection_details = requests.get(url, verify=False).json()\n",
    "\n",
    "        if connection_details[\"params\"][\"READER\"][\"type\"] == \"RDBMS\":\n",
    "            if connection_details[\"params\"][\"READER\"][\"sub_type\"] == \"SNOWFLAKE\":\n",
    "                data_frame = get_snowflake_df(connection_details, row_count, strategy, filter_condition)\n",
    "            elif connection_details[\"params\"][\"READER\"][\"sub_type\"] == \"MYSQL\":\n",
    "                data_frame = get_mysql_df(connection_details, row_count, strategy, filter_condition)\n",
    "            elif connection_details[\"params\"][\"READER\"][\"sub_type\"] == \"HIVE\":\n",
    "                data_frame = get_hive_df(connection_details, project_id, row_count, strategy, user_id, filter_condition)\n",
    "            elif connection_details[\"params\"][\"READER\"][\"sub_type\"] == \"SQLSERVER\":\n",
    "                data_frame = get_sqlserver_df(connection_details, row_count, strategy, filter_condition)\n",
    "            elif connection_details[\"params\"][\"READER\"][\"sub_type\"] == \"POSTGRES\":\n",
    "                data_frame = get_postgres_df(connection_details, row_count, strategy, filter_condition)\n",
    "            else:\n",
    "                print(\"Reading dataframe using connector backend\")\n",
    "                # Need to install, git+https://gitlab+deploy-token-14:myUpFE_XRxShG53Hs6tV@git.lti-aiq.in/mosaic-decisions-2-0/mosaic-connector-python.git\n",
    "                from connector.mosaicio import MosaicioConnector\n",
    "                connector = MosaicioConnector()\n",
    "                data_frame = connector.getPandasDataFrame(\n",
    "                    param=connection_details[\"params\"],\n",
    "                    row_count=row_count,\n",
    "                    strategy=strategy\n",
    "                )\n",
    "        elif connection_details[\"params\"][\"READER\"][\"type\"] == \"FILE\":\n",
    "            if connection_details[\"params\"][\"READER_STORAGE\"][\"type\"] == \"AMAZONS3\":\n",
    "                data_frame = get_s3_df(connection_details, row_count, strategy)\n",
    "            elif connection_details[\"params\"][\"READER_STORAGE\"][\"type\"] == \"AZURE\":\n",
    "                data_frame = get_azureblob_df(connection_details, row_count, strategy)\n",
    "            elif connection_details[\"params\"][\"READER_STORAGE\"][\"type\"] == \"SFTP\":\n",
    "                data_frame = get_sftp_df(connection_details, row_count, strategy)\n",
    "        return data_frame\n",
    "    except Exception as ex:\n",
    "        print(f'project_id: {project_id}')\n",
    "        print(f\"Connection details fetched: {connection_details}\")\n",
    "        print(f\"Exception occurred in get_dataframe: {ex}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b2640dd7",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_snowflake_df(connection_details, row_count, strategy, filter_condition):\n",
    "    \"\"\"\n",
    "    Param:\n",
    "        connection_details: connection details dict\n",
    "        row_count: number of rows to be fetched\n",
    "        strategy: top/bottom\n",
    "    To read data frame form snowflake connection\n",
    "    \"\"\"\n",
    "    print(\"Reading dataframe from snowflake native connector\")\n",
    "\n",
    "    import snowflake.connector\n",
    "\n",
    "    # Connect to Snowflake\n",
    "    con = snowflake.connector.connect(\n",
    "        user=connection_details[\"params\"][\"READER\"][\"user\"],\n",
    "        password=connection_details[\"params\"][\"READER\"][\"password\"],\n",
    "        account=connection_details[\"params\"][\"READER\"][\"accountId\"],\n",
    "        database=connection_details[\"params\"][\"READER\"][\"database\"],\n",
    "        role=connection_details[\"params\"][\"READER\"][\"role\"],\n",
    "        cloudPlatform=connection_details[\"params\"][\"READER\"][\"cloudPlatform\"],\n",
    "        schema=connection_details[\"params\"][\"READER\"][\"schema\"],\n",
    "        wareHouse=connection_details[\"params\"][\"READER\"][\"wareHouse\"],\n",
    "        region=connection_details[\"params\"][\"READER\"][\"region\"] + \".gcp\" if connection_details[\"params\"][\"READER\"][\"cloudPlatform\"] == \"gcp\" else connection_details[\"params\"][\"READER\"][\"region\"]\n",
    "    )\n",
    "    # Create cursor\n",
    "    cur = con.cursor()\n",
    "    query = get_dataframe_query(connection_details['params']['READER']['tables'],\n",
    "                                row_count, filter_condition, double_quotes=True)  # Get query to fetch details\n",
    "\n",
    "    cur.execute(f\"use warehouse {connection_details['params']['READER']['wareHouse']};\")  # Setting up warehouse, it is needed in new snowflake gcp connections.\n",
    "\n",
    "    cur.execute(query)  # Execute query\n",
    "\n",
    "    # Read results into a pandas DataFrame\n",
    "    data_frame = cur.fetch_pandas_all()\n",
    "\n",
    "    # Close cursor and connection\n",
    "    cur.close()\n",
    "    con.close()\n",
    "    return data_frame\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "46ca48d5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "project_id: a88ce554-9358-4397-8b8d-14c972807df5\n"
     ]
    },
    {
     "ename": "UnboundLocalError",
     "evalue": "local variable 'connection_details' referenced before assignment",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 16\u001b[0m, in \u001b[0;36mget_dataframe\u001b[0;34m(ds_name, project_id, row_count, strategy, user_id, filter_condition)\u001b[0m\n\u001b[1;32m     15\u001b[0m connection_manager\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhttp://fdc-project-manager:80/project-manager\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m---> 16\u001b[0m project_id \u001b[38;5;241m=\u001b[39m \u001b[43mvalidate_project_id\u001b[49m(project_id)\n\u001b[1;32m     17\u001b[0m url \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mconnection_manager\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m/connections/api/External/v2/external/getConnConfig/\u001b[39m\u001b[38;5;124m\"\u001b[39m \\\n\u001b[1;32m     18\u001b[0m       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mds_name\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m/fdcuser/\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mproject_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m    \u001b[38;5;66;03m# user id hard coded, as it's not being used in API code.\u001b[39;00m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'validate_project_id' is not defined",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mUnboundLocalError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[7], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m df \u001b[38;5;241m=\u001b[39m \u001b[43mget_dataframe\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mMENU\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[0;32mIn[5], line 52\u001b[0m, in \u001b[0;36mget_dataframe\u001b[0;34m(ds_name, project_id, row_count, strategy, user_id, filter_condition)\u001b[0m\n\u001b[1;32m     50\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m ex:\n\u001b[1;32m     51\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mproject_id: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mproject_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m---> 52\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mConnection details fetched: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mconnection_details\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     53\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mException occurred in get_dataframe: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mex\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mUnboundLocalError\u001b[0m: local variable 'connection_details' referenced before assignment"
     ]
    }
   ],
   "source": [
    "df = get_dataframe(\"MENU\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "06835bfe",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
